version: "3.7"

services:

  # PHP FPM
  php-fpm:
    build: './docker/php-fpm'
    container_name: crm_ipl_php-fpm2
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=symfony-demo"
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app

  # Nginx
  nginx:
    image: nginx:1.15
    container_name: crm_ipl_nginx1
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: crm_ipl_mysql1
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./var/mysql:/var/lib/mysql
      - ./docker/etc/mysql:/etc/mysql/conf.d
    ports:
      - 3308:3306
    env_file:
      - '.env.local'
  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_CLIENT_ID=950fbe49-8fff-4adf-8fa9-f45a787ede6e
      - BLACKFIRE_CLIENT_TOKEN=53f39f7c376cccee5b8258d08dd9b8f49ab0adfc2b77411536e1f85cec3ce635
      - BLACKFIRE_SERVER_ID=9c7ba2c9-5dfb-46f9-aee6-a074128f299e
      - BLACKFIRE_SERVER_TOKEN=65adc03c4079575a624f90f2ae44cbb8120ee9553f93b17969f542d870af040a
